### ISSUE TITLE
Nethermind update not compatible 

### ISSUE THREAD

**Issue by InoMurko** [dappnode/DAppNodePackage-nethermind-generic#11]
dappnode package not compatible 

![image](https://github.com/user-attachments/assets/b75657dc-1ec7-496c-9a2b-8f5be45b5511)

**Comment by Marketen** [comment]
@InoMurko This is a known bug of some of the latest execution client & consensus client releases. To fix it, try switching your IPFS repository from local to remote or viceversa. If this doesnt work, uninstall your consensus client (in your case, seems to be teku)  and try to update nethermind again. Your consensus client will resync again in a few minutes thanks to checkpoint sync.
